# Generated by Django 4.1.1 on 2022-10-17 07:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkTemplate",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Когда создан"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Когда изменён"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название шаблона"),
                ),
                ("url", models.CharField(max_length=255, verbose_name="Ссылка")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Когда создан"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Когда изменён"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "times_followed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество переходов по ссылке"
                    ),
                ),
                ("long_url", models.URLField(verbose_name="Изначальный URL")),
                (
                    "short_url",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        unique=True,
                        verbose_name="Код",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("dirty", "dirty"),
                            ("ready", "ready"),
                            ("shorter", "shorter"),
                            ("during", "during"),
                        ],
                        default="dirty",
                        max_length=255,
                        verbose_name="Статус ссылки",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="own_links",
                        to="files.session",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
    ]
