# Generated by Django 4.1.1 on 2022-10-09 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0002_rename_file_session_and_more"),
        ("shortener", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="session",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="own_links",
                to="files.session",
            ),
        ),
    ]
