# Generated by Django 4.1.1 on 2022-10-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0003_linktemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="linktemplate",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Когда создан"
            ),
        ),
        migrations.AddField(
            model_name="linktemplate",
            name="modified",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Когда изменён"
            ),
        ),
    ]
