# Generated by Django 4.1.1 on 2022-10-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0004_linktemplate_created_linktemplate_modified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="linktemplate",
            name="url",
            field=models.CharField(max_length=255, verbose_name="Ссылка"),
        ),
    ]
