# Generated by Django 4.1.1 on 2022-10-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0006_alter_link_id_alter_linktemplate_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="linktemplate",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
