# Generated by Django 4.1.1 on 2022-10-12 07:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0007_alter_link_id_alter_linktemplate_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="linktemplate",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
