# Generated by Django 4.1.1 on 2022-10-12 07:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0008_alter_linktemplate_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
