# Generated by Django 4.1.1 on 2022-10-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "input_excel_file",
                    models.FileField(blank=True, null=True, upload_to="input"),
                ),
                (
                    "zip_file",
                    models.FileField(blank=True, null=True, upload_to="zip_files"),
                ),
                (
                    "output_excel_file",
                    models.FileField(blank=True, null=True, upload_to="output"),
                ),
            ],
        ),
    ]
