# Generated by Django 4.1.1 on 2022-10-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Когда создан"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Когда изменён"
                    ),
                ),
                (
                    "times_followed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество переходов по ссылке"
                    ),
                ),
                ("long_url", models.URLField(verbose_name="Изначальный URL")),
                (
                    "short_url",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        unique=True,
                        verbose_name="Код",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("dirty", "dirty"),
                            ("ready", "ready"),
                            ("shorter", "shorter"),
                            ("during", "during"),
                        ],
                        default="dirty",
                        max_length=255,
                        verbose_name="Статус ссылки",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
    ]
