# Generated by Django 4.1.1 on 2022-10-09 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0001_initial"),
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="File",
            new_name="Session",
        ),
        migrations.RenameField(
            model_name="session",
            old_name="input_excel_file",
            new_name="input_file",
        ),
        migrations.RenameField(
            model_name="session",
            old_name="output_excel_file",
            new_name="output_file",
        ),
    ]
