# Generated by Django 4.1.1 on 2022-10-12 07:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0002_rename_file_session_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
